## Задание 1

Импортируйте библиотеку **Numpy** и дайте ей псевдоним np.

In [1]:
import numpy as np

Создайте массив Numpy под названием **a** размером **5x2**, то есть состоящий из **5** строк и **2** столбцов. Первый столбец должен содержать числа **1, 2, 3, 3, 1**, а второй - числа **6, 8, 11, 10, 7**. Будем считать, что каждый столбец - это признак, а строка - наблюдение. 

In [15]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Затем найдите среднее значение по каждому признаку, используя метод **mean** массива **Numpy**. Результат запишите в массив **mean_a**, в нем должно быть **2** элемента.

In [19]:
mean_a = np.mean(a, axis=0).reshape(1,2)
mean_a

array([[2. , 8.4]])

## Задание 2
Вычислите массив **a_centered**, отняв от значений массива **“а”** средние значения соответствующих признаков, содержащиеся в массиве **mean_a**. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер **5x2**.

In [20]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

Найдите скалярное произведение столбцов массива **a_centered**. В результате должна получиться величина **a_centered_sp**. Затем поделите **a_centered_sp** на **N-1**, где **N** - число наблюдений.

In [29]:
a_centered_sp = (a_centered[:, 0] @ a_centered[:, 1]) / 4
a_centered_sp

2.0

## Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве **“а”**. В задании 4 мы делили сумму произведений центрированных признаков на **N-1**, а не на **N**, поэтому полученная нами величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции **np.cov**. В качестве аргумента **m** функция **np.cov** должна принимать транспонированный массив **“a”**. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом **0** и столбце с индексом **1**.

In [25]:
a_centered_sp_theor = np.cov(a.transpose())
a_centered_sp_theor

array([[1. , 2. ],
       [2. , 4.3]])

## Задание 5**

Создайте одномерный массив **z** случайных целых чисел из равномерного распределения от **-50** до **50** включительно размерности **8**. Найдите индексы положительных объектов.

In [38]:
z = np.random.uniform(-50, 50, (1,8))
np.where(z >= 0)[1]

array([0, 6, 7])

## Задание 6**

Создайте двумерный массив **X** случайных равномерно распределенных целых чисел от **0** до **255** включительно размерности **10** на **5**.

In [39]:
X = np.random.uniform(0, 255, (10, 5))
X

array([[132.63346833, 225.27427287, 231.944764  , 113.6055138 ,
        155.29689056],
       [183.69845435,  77.223009  , 115.49999324, 157.208616  ,
        180.58215938],
       [171.67670974, 193.61789709, 199.77153004,  96.03439679,
        193.31138213],
       [ 12.31515714,  82.91937651, 244.28314047, 175.27996552,
        213.5758591 ],
       [182.19079587, 157.73106231,  18.52838032, 145.79623738,
        179.64682334],
       [ 40.10960139,  77.33805508, 105.37077051,  92.47091316,
         49.76964061],
       [252.74227789,  74.42244073, 250.70930669, 205.24605964,
         21.14922652],
       [112.02299482, 114.06810642, 166.25142686, 133.16455135,
        211.74265666],
       [ 90.41025793,  67.25573622,  55.08964648, 121.31772403,
        168.76797651],
       [131.48608802, 133.86031927,  99.02332385, 127.4429392 ,
         80.99645653]])

Найдите среднее значение и стандартное отклонение по каждому признаку.

In [41]:
mean_X, std_X = X.mean(axis=0), X.std(axis=0)
mean_X, std_X

(array([130.92858055, 120.37102755, 148.64722825, 136.75669169,
        145.48390714]),
 array([67.99343018, 52.94900941, 77.80940536, 33.41908802, 65.67389342]))

Вычислите массив **X_standard**, отняв от каждого признака среднее и поделив на стандартное отклонение.
Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице.
Это называется стандартизация данных - важный процесс подготовки данных. Более подробно можно почитать здесь 

In [43]:
X_standard = (X - mean_X) / std_X
X_standard

array([[ 0.0250743 ,  1.98121261,  1.07053299, -0.69275313,  0.14941985],
       [ 0.77610254, -0.81489756, -0.4260055 ,  0.61198332,  0.53443234],
       [ 0.59929509,  1.38334731,  0.65704527, -1.218534  ,  0.72825704],
       [-1.74448359, -0.70731542,  1.22910478,  1.15273265,  1.03681917],
       [ 0.75392895,  0.70558515, -1.6722766 ,  0.2704905 ,  0.52019021],
       [-1.33570227, -0.81272479, -0.55618543, -1.32516418, -1.45741727],
       [ 1.79155099, -0.86778936,  1.31169334,  2.04940865, -1.89321318],
       [-0.27805018, -0.11903756,  0.2262477 , -0.10748768,  1.00890546],
       [-0.59591526, -1.00314042, -1.20239425, -0.46198052,  0.35454072],
       [ 0.00819943,  0.25476004, -0.63776229, -0.27869559, -0.98193433]])

In [44]:
X_standard.mean(axis=0), X_standard.std(axis=0)

(array([-1.96717642e-16, -3.33066907e-16,  1.55431223e-16,  5.44009282e-16,
        -2.22044605e-17]),
 array([1., 1., 1., 1., 1.]))

## Задание 7**

Создайте два одномерных массива размерности **512** с любыми значениями. Будем считать, что каждый массив - это наблюдение с **512** признаками. 

In [45]:
a = np.random.randint(0, 100, (1, 512))
b = np.random.randint(0, 100, (1, 512))

Найдите разницу между двумя массивами. Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный.

Это получилась **L2-норма** (Евклидова метрика) — функция расстояния, благодаря которой можно считать насколько далеки точки друг от друга, насколько они похожи друг на друга. 

Посчитайте **L2** норму для этих двух массивов с помощью **numpy.linalg**.

In [47]:
l2 = np.sqrt(np.sum(np.power(a-b,2)))
l2

947.4249310631424

In [50]:
l2_theory = np.linalg.norm(a - b, axis=1)
l2_theory

array([947.42493106])

## Задание 8**

Используйте ранее созданный массив X. Найдите минимальное значение и максимальное по каждому признаку.

In [51]:
min_X, max_X = X.min(), X.max()
min_X, max_X

(12.31515714456057, 252.74227788850106)

Вычислите массив X_norm, отняв от каждого признака минимальное и поделив на разницу максимального и минимального.
Убедитесь, что теперь минимальное значение стало равно 0, а максимальное - 1.
Это называется нормализация данных - еще один из важных процессов подготовки данных.

In [55]:
X_norm = (X - min_X) / (max_X - min_X)
X_norm.min(), X_norm.max()

(0.0, 1.0)